## Install Numpy

In [1]:
#pip install numpy

### Once you've installed NumPy you can import it

In [2]:
import numpy as np

## Creating numpy array

In [3]:
my_list = [1, 3, 2]
my_list

[1, 3, 2]

In [4]:
arr = np.array(my_list)     # list convert in array
arr

array([1, 3, 2])

In [5]:
my_matrix = [[1, 3, 4], [2, 4, 5], [34, 4, 6]]
np.array(my_matrix)

array([[ 1,  3,  4],
       [ 2,  4,  5],
       [34,  4,  6]])

## Built-in Methods

### 1. arange
Return evenly spaced values within a given interval.

In [6]:
np.arange(10)  
#OR
np.arange(0, 10)     #np.arange(start = 0, stop = 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)      #np.arange(start = 0, stop = 10, step = 2)

array([0, 2, 4, 6, 8])

### 2. zeros and ones
Generate arrays of zeros or ones.

In [8]:
np.zeros((3))

array([0., 0., 0.])

In [9]:
np.zeros((2, 2))    #np.zeros((rows, columns))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.zeros((3, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((2, 2))       #np.ones((rows, columns))

array([[1., 1.],
       [1., 1.]])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 3. empty

In [14]:
np.empty((2))

array([2.55982669e-288, 8.22088488e-109])

### 4. linspace
create an array with values that are spaced linearly in a specified interval

In [15]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### 5. eye
Creates an identity matrix

In [17]:
np.eye(4)     # diagonal matrix (4*4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6. Random

Numpy also has lots of ways to create random number arrays:

**A. rand =>** Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [18]:
np.random.rand(3)      #generate random number between 0 & 1

array([0.10811286, 0.23637663, 0.73227898])

In [19]:
np.random.rand(3, 3)

array([[0.40350362, 0.54882095, 0.40231594],
       [0.45239185, 0.00108434, 0.43299133],
       [0.78935316, 0.20015052, 0.01140282]])

**B. randn =>**
Return a sample from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(3)

array([ 0.56992279, -1.30436031, -1.66654225])

In [21]:
np.random.randn(3, 4)

array([[-0.0751837 , -1.04321061, -0.58786085, -0.70249515],
       [-0.81105089, -1.4085294 , -0.64669793, -0.41070377],
       [-1.22124143, -0.16732305, -0.2063695 , -0.49882499]])

**C. randint =>**
Return random integers from low (inclusive) to high (exclusive).

In [22]:
np.random.randint(10)
#OR
np.random.randint(0, 10)   # np.random.randint(inclusive, exclusive)

9

In [23]:
np.random.randint(0, 10, 5)   # np.random.randint(lowest value, highest value, size of array)

array([1, 8, 5, 9, 4])

## Array Attributes and Methods

In [24]:
arr = np.arange(0, 15)

random_arr = np.random.randint(1, 50, 10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
random_arr

array([41, 46, 31, 42, 16,  4, 27, 43, 43,  9])

### 1. Reshape
Returns an array containing the same data with a new shape.

In [27]:
arr.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 2. Shape
Shape is an attribute that arrays have (not a method).

In [29]:
arr = np.arange(0, 15)      #its 1-D array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr.shape     #Vector

(15,)

In [31]:
arr.reshape(1, 15)     #its 2-D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [32]:
arr.reshape(1, 15).shape

(1, 15)

In [33]:
arr.reshape(15, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [34]:
arr.reshape(15, 1).shape

(15, 1)

### 3. dtype
We can also grab the data type of the object in the array.

In [35]:
arr.dtype

dtype('int32')

### 4. ndim
To find the number of dimensions of the array.

In [36]:
arr.ndim

1

### 5. Size
To find the total number of elements in the array.

In [37]:
arr.size

15

## Numpy Indexing and Selection

In [38]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**You can access an array element by referring to its index number like as list:**

In [39]:
# first valuet in array
arr[0]

1

In [40]:
# last value in array
arr[-1]

10

In [41]:
# get a value at an index
arr[7]

8

In [42]:
#Get values in a range
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[0:5]     # first 5 element

array([1, 2, 3, 4, 5])

In [45]:
arr[-5:]     # last 5 element

array([ 6,  7,  8,  9, 10])

In [46]:
arr[3:7]

array([4, 5, 6, 7])

### 1. Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast.

In [47]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# Setting a value with index range (Broadcasting)
arr[0:5] = 500
arr

array([500, 500, 500, 500, 500,   6,   7,   8,   9,  10])

In [49]:
slice_of_arr = arr[0:6]
slice_of_arr

array([500, 500, 500, 500, 500,   6])

**Note: Now note the changes also occur in our original array!**

In [50]:
slice_of_arr[:] = 55
slice_of_arr

array([55, 55, 55, 55, 55, 55])

**Data is not copied, it's a view of the original array! This avoids memory problems!**

In [51]:
arr

array([55, 55, 55, 55, 55, 55,  7,  8,  9, 10])

#### To get a copy, need to be explicit

In [52]:
arr = np.arange(1, 11)

arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2. Indexing a 2-D array (matrices)
The general format is arr_2d [row,col] OR arr_2d[row][col]. 
I recommend usually using the comma notation for clarity.

In [53]:
arr_2d = np.array([[1, 2, 4], [3, 25, 5], [6, 7, 9]])
arr_2d

array([[ 1,  2,  4],
       [ 3, 25,  5],
       [ 6,  7,  9]])

In [54]:
arr_2d[1]    # arr_2d[row]

array([ 3, 25,  5])

**Getting individual element value**

In [55]:
arr_2d[1, 1]    # arr_2d[row, col]
#OR
arr_2d[1][1]    # arr_2d[row][col]

25

#### 2D array slicing

In [56]:
# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 2,  4],
       [25,  5]])

In [57]:
# Shape bottom row
arr_2d[2]   
#OR
arr_2d[2, :]

array([6, 7, 9])

### 3. Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [58]:
arr = np.zeros((5, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
arr_length = arr.shape[1]
arr_length

5

In [60]:
for i in range(arr_length):
    arr[i] = i
    
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

### 4. Selection
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [61]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
arr > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
bool_arr = arr > 4
bool_arr

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
arr[arr >= 3]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
x = 5
arr[arr < x]

array([1, 2, 3, 4])

In [67]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [68]:
arr[(arr > 3) & (arr < 10)]

array([4, 5, 6, 7, 8, 9])

In [69]:
b = np.nonzero(arr < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


## NumPy Operations

### 1. Arithmetic
You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [70]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
arr ** 2       # square of array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
arr / 0    # NaN

C:\Users\Admin\AppData\Local\Temp\ipykernel_10080\4012733348.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0    # NaN


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

### 2. Universal Array Functions¶
Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array.

In [77]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [79]:
# Calcualting exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [80]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [81]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

### max, min, argmax, argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [82]:
arr.max()     # find max value in arr
#OR
np.max(arr)

10

In [83]:
arr.argmax()       # find the index location of max value
#OR
np.argmax(arr)

9

In [84]:
arr.min()     # find min value in arr
#OR
np.min(arr)

1

In [85]:
np.argmin(arr)     # find the index location of max value
#OR
np.argmin(arr)

0

In [86]:
arr.sum()

55

In [87]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
# You can reverse array
np.flip(arr)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Thanks!!